services:
  OTA-Hub_api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: OTA-Hub_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"